// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBulkCreateFileTags implements pgx.CopyFromSource.
type iteratorForBulkCreateFileTags struct {
	rows                 []BulkCreateFileTagsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateFileTags) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateFileTags) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].FileID,
		r.rows[0].UserID,
		r.rows[0].TagName,
	}, nil
}

func (r iteratorForBulkCreateFileTags) Err() error {
	return nil
}

func (q *Queries) BulkCreateFileTags(ctx context.Context, arg []BulkCreateFileTagsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"file_tags"}, []string{"file_id", "user_id", "tag_name"}, &iteratorForBulkCreateFileTags{rows: arg})
}
