// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerification = `-- name: CreateEmailVerification :one
INSERT INTO email_verifications (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, verified_at, created_at
`

type CreateEmailVerificationParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, createEmailVerification, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredEmailVerifications = `-- name: DeleteExpiredEmailVerifications :exec
DELETE FROM email_verifications
WHERE expires_at < NOW() OR verified_at IS NOT NULL
`

func (q *Queries) DeleteExpiredEmailVerifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredEmailVerifications)
	return err
}

const deleteUserEmailVerifications = `-- name: DeleteUserEmailVerifications :exec
DELETE FROM email_verifications WHERE user_id = $1
`

func (q *Queries) DeleteUserEmailVerifications(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserEmailVerifications, userID)
	return err
}

const getEmailVerificationByTokenHash = `-- name: GetEmailVerificationByTokenHash :one
SELECT ev.id, ev.user_id, ev.token_hash, ev.expires_at, ev.verified_at, ev.created_at, u.email, u.name
FROM email_verifications ev
JOIN users u ON ev.user_id = u.id
WHERE ev.token_hash = $1 
  AND ev.expires_at > NOW() 
  AND ev.verified_at IS NULL
  AND u.deleted_at IS NULL
`

type GetEmailVerificationByTokenHashRow struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Email      string             `json:"email"`
	Name       string             `json:"name"`
}

func (q *Queries) GetEmailVerificationByTokenHash(ctx context.Context, tokenHash string) (GetEmailVerificationByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationByTokenHash, tokenHash)
	var i GetEmailVerificationByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
	)
	return i, err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE email_verifications
SET verified_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}
