// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO processing_jobs (
    file_id,
    job_type,
    priority
) VALUES (
    $1, $2, $3
)
RETURNING id, file_id, job_type, status, priority, attempts, error_message, created_at, started_at, completed_at
`

type CreateJobParams struct {
	FileID   pgtype.UUID `json:"file_id"`
	JobType  JobType     `json:"job_type"`
	Priority int32       `json:"priority"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (ProcessingJob, error) {
	row := q.db.QueryRow(ctx, createJob, arg.FileID, arg.JobType, arg.Priority)
	var i ProcessingJob
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.JobType,
		&i.Status,
		&i.Priority,
		&i.Attempts,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteJobsByFileID = `-- name: DeleteJobsByFileID :exec
DELETE FROM processing_jobs
WHERE file_id = $1
`

func (q *Queries) DeleteJobsByFileID(ctx context.Context, fileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteJobsByFileID, fileID)
	return err
}

const getJob = `-- name: GetJob :one
SELECT id, file_id, job_type, status, priority, attempts, error_message, created_at, started_at, completed_at FROM processing_jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id pgtype.UUID) (ProcessingJob, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i ProcessingJob
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.JobType,
		&i.Status,
		&i.Priority,
		&i.Attempts,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listJobsByFileID = `-- name: ListJobsByFileID :many
SELECT id, file_id, job_type, status, priority, attempts, error_message, created_at, started_at, completed_at FROM processing_jobs
WHERE file_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListJobsByFileID(ctx context.Context, fileID pgtype.UUID) ([]ProcessingJob, error) {
	rows, err := q.db.Query(ctx, listJobsByFileID, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProcessingJob
	for rows.Next() {
		var i ProcessingJob
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.JobType,
			&i.Status,
			&i.Priority,
			&i.Attempts,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingJobs = `-- name: ListPendingJobs :many
SELECT id, file_id, job_type, status, priority, attempts, error_message, created_at, started_at, completed_at FROM processing_jobs
WHERE status = 'pending'
ORDER BY priority DESC, created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingJobs(ctx context.Context, limit int32) ([]ProcessingJob, error) {
	rows, err := q.db.Query(ctx, listPendingJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProcessingJob
	for rows.Next() {
		var i ProcessingJob
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.JobType,
			&i.Status,
			&i.Priority,
			&i.Attempts,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobCompleted = `-- name: MarkJobCompleted :exec
UPDATE processing_jobs
SET status = 'completed',
    completed_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkJobCompleted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markJobCompleted, id)
	return err
}

const markJobFailed = `-- name: MarkJobFailed :exec
UPDATE processing_jobs
SET status = 'failed',
    completed_at = NOW(),
    error_message = $2
WHERE id = $1
`

type MarkJobFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage *string     `json:"error_message"`
}

func (q *Queries) MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) error {
	_, err := q.db.Exec(ctx, markJobFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markJobRunning = `-- name: MarkJobRunning :exec
UPDATE processing_jobs
SET status = 'running',
    started_at = NOW(),
    attempts = attempts + 1
WHERE id = $1
`

func (q *Queries) MarkJobRunning(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markJobRunning, id)
	return err
}
