// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type FileStatus string

const (
	FileStatusPending    FileStatus = "pending"
	FileStatusProcessing FileStatus = "processing"
	FileStatusCompleted  FileStatus = "completed"
	FileStatusFailed     FileStatus = "failed"
)

func (e *FileStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FileStatus(s)
	case string:
		*e = FileStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FileStatus: %T", src)
	}
	return nil
}

type NullFileStatus struct {
	FileStatus FileStatus `json:"file_status"`
	Valid      bool       `json:"valid"` // Valid is true if FileStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFileStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FileStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FileStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFileStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FileStatus), nil
}

type JobStatus string

const (
	JobStatusPending   JobStatus = "pending"
	JobStatusRunning   JobStatus = "running"
	JobStatusCompleted JobStatus = "completed"
	JobStatusFailed    JobStatus = "failed"
)

func (e *JobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobStatus(s)
	case string:
		*e = JobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for JobStatus: %T", src)
	}
	return nil
}

type NullJobStatus struct {
	JobStatus JobStatus `json:"job_status"`
	Valid     bool      `json:"valid"` // Valid is true if JobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.JobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobStatus), nil
}

type JobType string

const (
	JobTypeThumbnail    JobType = "thumbnail"
	JobTypeResize       JobType = "resize"
	JobTypeWebp         JobType = "webp"
	JobTypeWatermark    JobType = "watermark"
	JobTypePdfThumbnail JobType = "pdf_thumbnail"
	JobTypeMetadata     JobType = "metadata"
	JobTypeOptimize     JobType = "optimize"
)

func (e *JobType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobType(s)
	case string:
		*e = JobType(s)
	default:
		return fmt.Errorf("unsupported scan type for JobType: %T", src)
	}
	return nil
}

type NullJobType struct {
	JobType JobType `json:"job_type"`
	Valid   bool    `json:"valid"` // Valid is true if JobType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobType) Scan(value interface{}) error {
	if value == nil {
		ns.JobType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobType), nil
}

type OauthProvider string

const (
	OauthProviderGoogle OauthProvider = "google"
	OauthProviderGithub OauthProvider = "github"
)

func (e *OauthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OauthProvider(s)
	case string:
		*e = OauthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for OauthProvider: %T", src)
	}
	return nil
}

type NullOauthProvider struct {
	OauthProvider OauthProvider `json:"oauth_provider"`
	Valid         bool          `json:"valid"` // Valid is true if OauthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOauthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.OauthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OauthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOauthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OauthProvider), nil
}

type UserRole string

const (
	UserRoleUser  UserRole = "user"
	UserRoleAdmin UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type VariantType string

const (
	VariantTypeThumbnail   VariantType = "thumbnail"
	VariantTypeLarge       VariantType = "large"
	VariantTypeMedium      VariantType = "medium"
	VariantTypeSmall       VariantType = "small"
	VariantTypeWebp        VariantType = "webp"
	VariantTypeWatermarked VariantType = "watermarked"
	VariantTypeOptimized   VariantType = "optimized"
	VariantTypePdfPreview  VariantType = "pdf_preview"
)

func (e *VariantType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VariantType(s)
	case string:
		*e = VariantType(s)
	default:
		return fmt.Errorf("unsupported scan type for VariantType: %T", src)
	}
	return nil
}

type NullVariantType struct {
	VariantType VariantType `json:"variant_type"`
	Valid       bool        `json:"valid"` // Valid is true if VariantType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVariantType) Scan(value interface{}) error {
	if value == nil {
		ns.VariantType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VariantType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVariantType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VariantType), nil
}

type ApiToken struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type EmailVerification struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type File struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Filename    string             `json:"filename"`
	ContentType string             `json:"content_type"`
	SizeBytes   int64              `json:"size_bytes"`
	StorageKey  string             `json:"storage_key"`
	Status      FileStatus         `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type FileVariant struct {
	ID          pgtype.UUID        `json:"id"`
	FileID      pgtype.UUID        `json:"file_id"`
	VariantType VariantType        `json:"variant_type"`
	ContentType string             `json:"content_type"`
	SizeBytes   int64              `json:"size_bytes"`
	StorageKey  string             `json:"storage_key"`
	Width       *int32             `json:"width"`
	Height      *int32             `json:"height"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type OauthAccount struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Provider       OauthProvider      `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	AccessToken    *string            `json:"access_token"`
	RefreshToken   *string            `json:"refresh_token"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PasswordReset struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ProcessingJob struct {
	ID           pgtype.UUID        `json:"id"`
	FileID       pgtype.UUID        `json:"file_id"`
	JobType      JobType            `json:"job_type"`
	Status       JobStatus          `json:"status"`
	Priority     int32              `json:"priority"`
	Attempts     int32              `json:"attempts"`
	ErrorMessage *string            `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	UserAgent *string            `json:"user_agent"`
	IpAddress *netip.Addr        `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    *string            `json:"password_hash"`
	Name            string             `json:"name"`
	AvatarUrl       *string            `json:"avatar_url"`
	Role            UserRole           `json:"role"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type UserSetting struct {
	ID                   pgtype.UUID        `json:"id"`
	UserID               pgtype.UUID        `json:"user_id"`
	EmailNotifications   bool               `json:"email_notifications"`
	ProcessingAlerts     bool               `json:"processing_alerts"`
	MarketingEmails      bool               `json:"marketing_emails"`
	DefaultRetentionDays int32              `json:"default_retention_days"`
	AutoDeleteOriginals  bool               `json:"auto_delete_originals"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}
