// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeOnboarding = `-- name: CompleteOnboarding :exec
UPDATE users
SET onboarding_completed_at = NOW()
WHERE id = $1 AND onboarding_completed_at IS NULL
`

func (q *Queries) CompleteOnboarding(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, completeOnboarding, id)
	return err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, title, message, link)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, title, message, link, read_at, created_at
`

type CreateNotificationParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Type    string      `json:"type"`
	Title   string      `json:"title"`
	Message string      `json:"message"`
	Link    *string     `json:"link"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.Link,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.Link,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications WHERE id = $1 AND user_id = $2
`

type DeleteNotificationParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.UserID)
	return err
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications
WHERE created_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) DeleteOldNotifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldNotifications)
	return err
}

const getNotification = `-- name: GetNotification :one
SELECT id, user_id, type, title, message, link, read_at, created_at FROM notifications WHERE id = $1
`

func (q *Queries) GetNotification(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.Link,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserOnboardingProgress = `-- name: GetUserOnboardingProgress :one
SELECT
    onboarding_completed_at,
    onboarding_steps
FROM users
WHERE id = $1
`

type GetUserOnboardingProgressRow struct {
	OnboardingCompletedAt pgtype.Timestamptz `json:"onboarding_completed_at"`
	OnboardingSteps       []byte             `json:"onboarding_steps"`
}

func (q *Queries) GetUserOnboardingProgress(ctx context.Context, id pgtype.UUID) (GetUserOnboardingProgressRow, error) {
	row := q.db.QueryRow(ctx, getUserOnboardingProgress, id)
	var i GetUserOnboardingProgressRow
	err := row.Scan(&i.OnboardingCompletedAt, &i.OnboardingSteps)
	return i, err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, user_id, type, title, message, link, read_at, created_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Link,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotificationsByUser = `-- name: ListUnreadNotificationsByUser :many
SELECT id, user_id, type, title, message, link, read_at, created_at FROM notifications
WHERE user_id = $1 AND read_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type ListUnreadNotificationsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListUnreadNotificationsByUser(ctx context.Context, arg ListUnreadNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnreadNotificationsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Link,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET read_at = NOW()
WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET read_at = NOW()
WHERE id = $1 AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}

const updateOnboardingStep = `-- name: UpdateOnboardingStep :exec
UPDATE users
SET onboarding_steps = onboarding_steps || $2::jsonb
WHERE id = $1
`

type UpdateOnboardingStepParams struct {
	ID      pgtype.UUID `json:"id"`
	Column2 []byte      `json:"column_2"`
}

func (q *Queries) UpdateOnboardingStep(ctx context.Context, arg UpdateOnboardingStepParams) error {
	_, err := q.db.Exec(ctx, updateOnboardingStep, arg.ID, arg.Column2)
	return err
}
