// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_accounts (user_id, provider, provider_user_id, access_token, refresh_token, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, provider, provider_user_id, access_token, refresh_token, expires_at, created_at
`

type CreateOAuthAccountParams struct {
	UserID         pgtype.UUID        `json:"user_id"`
	Provider       OauthProvider      `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	AccessToken    *string            `json:"access_token"`
	RefreshToken   *string            `json:"refresh_token"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOAuthAccount = `-- name: DeleteOAuthAccount :exec
DELETE FROM oauth_accounts
WHERE user_id = $1 AND provider = $2
`

type DeleteOAuthAccountParams struct {
	UserID   pgtype.UUID   `json:"user_id"`
	Provider OauthProvider `json:"provider"`
}

func (q *Queries) DeleteOAuthAccount(ctx context.Context, arg DeleteOAuthAccountParams) error {
	_, err := q.db.Exec(ctx, deleteOAuthAccount, arg.UserID, arg.Provider)
	return err
}

const getOAuthAccount = `-- name: GetOAuthAccount :one
SELECT id, user_id, provider, provider_user_id, access_token, refresh_token, expires_at, created_at FROM oauth_accounts
WHERE provider = $1 AND provider_user_id = $2
`

type GetOAuthAccountParams struct {
	Provider       OauthProvider `json:"provider"`
	ProviderUserID string        `json:"provider_user_id"`
}

func (q *Queries) GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccount, arg.Provider, arg.ProviderUserID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthAccountWithUser = `-- name: GetOAuthAccountWithUser :one
SELECT 
    oa.id, oa.user_id, oa.provider, oa.provider_user_id, oa.access_token, oa.refresh_token, oa.expires_at, oa.created_at,
    u.email, u.name, u.avatar_url, u.role, u.email_verified_at, u.created_at as user_created_at
FROM oauth_accounts oa
JOIN users u ON oa.user_id = u.id
WHERE oa.provider = $1 AND oa.provider_user_id = $2 AND u.deleted_at IS NULL
`

type GetOAuthAccountWithUserParams struct {
	Provider       OauthProvider `json:"provider"`
	ProviderUserID string        `json:"provider_user_id"`
}

type GetOAuthAccountWithUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Provider        OauthProvider      `json:"provider"`
	ProviderUserID  string             `json:"provider_user_id"`
	AccessToken     *string            `json:"access_token"`
	RefreshToken    *string            `json:"refresh_token"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Email           string             `json:"email"`
	Name            string             `json:"name"`
	AvatarUrl       *string            `json:"avatar_url"`
	Role            UserRole           `json:"role"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	UserCreatedAt   pgtype.Timestamptz `json:"user_created_at"`
}

func (q *Queries) GetOAuthAccountWithUser(ctx context.Context, arg GetOAuthAccountWithUserParams) (GetOAuthAccountWithUserRow, error) {
	row := q.db.QueryRow(ctx, getOAuthAccountWithUser, arg.Provider, arg.ProviderUserID)
	var i GetOAuthAccountWithUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.EmailVerifiedAt,
		&i.UserCreatedAt,
	)
	return i, err
}

const listUserOAuthAccounts = `-- name: ListUserOAuthAccounts :many
SELECT id, user_id, provider, provider_user_id, access_token, refresh_token, expires_at, created_at FROM oauth_accounts
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserOAuthAccounts(ctx context.Context, userID pgtype.UUID) ([]OauthAccount, error) {
	rows, err := q.db.Query(ctx, listUserOAuthAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthAccount
	for rows.Next() {
		var i OauthAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOAuthTokens = `-- name: UpdateOAuthTokens :exec
UPDATE oauth_accounts
SET access_token = $3, refresh_token = $4, expires_at = $5
WHERE provider = $1 AND provider_user_id = $2
`

type UpdateOAuthTokensParams struct {
	Provider       OauthProvider      `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	AccessToken    *string            `json:"access_token"`
	RefreshToken   *string            `json:"refresh_token"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateOAuthTokens(ctx context.Context, arg UpdateOAuthTokensParams) error {
	_, err := q.db.Exec(ctx, updateOAuthTokens,
		arg.Provider,
		arg.ProviderUserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	return err
}
