// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelUserSubscription = `-- name: CancelUserSubscription :one
UPDATE users
SET 
    stripe_subscription_id = NULL,
    subscription_status = 'canceled',
    subscription_tier = 'free',
    files_limit = 100,
    max_file_size = 10485760,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, name, avatar_url, role, subscription_tier, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_period_end, trial_ends_at, files_limit, max_file_size, storage_limit_bytes, storage_used_bytes, transformations_count, transformations_limit, transformations_reset_at, email_verified_at, onboarding_completed_at, onboarding_steps, created_at, updated_at, deleted_at
`

func (q *Queries) CancelUserSubscription(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, cancelUserSubscription, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.SubscriptionTier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionPeriodEnd,
		&i.TrialEndsAt,
		&i.FilesLimit,
		&i.MaxFileSize,
		&i.StorageLimitBytes,
		&i.StorageUsedBytes,
		&i.TransformationsCount,
		&i.TransformationsLimit,
		&i.TransformationsResetAt,
		&i.EmailVerifiedAt,
		&i.OnboardingCompletedAt,
		&i.OnboardingSteps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersForAdmin = `-- name: CountUsersForAdmin :one
SELECT COUNT(*)
FROM users
WHERE deleted_at IS NULL
    AND ($1::text = '' OR email ILIKE '%' || $1 || '%' OR name ILIKE '%' || $1 || '%')
`

func (q *Queries) CountUsersForAdmin(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersForAdmin, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, name, avatar_url, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, name, avatar_url, role, subscription_tier, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_period_end, trial_ends_at, files_limit, max_file_size, storage_limit_bytes, storage_used_bytes, transformations_count, transformations_limit, transformations_reset_at, email_verified_at, onboarding_completed_at, onboarding_steps, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Email        string   `json:"email"`
	PasswordHash *string  `json:"password_hash"`
	Name         string   `json:"name"`
	AvatarUrl    *string  `json:"avatar_url"`
	Role         UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.AvatarUrl,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.SubscriptionTier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionPeriodEnd,
		&i.TrialEndsAt,
		&i.FilesLimit,
		&i.MaxFileSize,
		&i.StorageLimitBytes,
		&i.StorageUsedBytes,
		&i.TransformationsCount,
		&i.TransformationsLimit,
		&i.TransformationsResetAt,
		&i.EmailVerifiedAt,
		&i.OnboardingCompletedAt,
		&i.OnboardingSteps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const decrementUserStorageUsed = `-- name: DecrementUserStorageUsed :exec
UPDATE users
SET storage_used_bytes = GREATEST(0, storage_used_bytes - $2), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type DecrementUserStorageUsedParams struct {
	ID               pgtype.UUID `json:"id"`
	StorageUsedBytes int64       `json:"storage_used_bytes"`
}

func (q *Queries) DecrementUserStorageUsed(ctx context.Context, arg DecrementUserStorageUsedParams) error {
	_, err := q.db.Exec(ctx, decrementUserStorageUsed, arg.ID, arg.StorageUsedBytes)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserBillingInfo = `-- name: GetUserBillingInfo :one
SELECT 
    id,
    email,
    name,
    subscription_tier,
    stripe_customer_id,
    stripe_subscription_id,
    subscription_status,
    subscription_period_end,
    trial_ends_at,
    files_limit,
    max_file_size,
    transformations_count,
    transformations_limit,
    transformations_reset_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserBillingInfoRow struct {
	ID                     pgtype.UUID        `json:"id"`
	Email                  string             `json:"email"`
	Name                   string             `json:"name"`
	SubscriptionTier       SubscriptionTier   `json:"subscription_tier"`
	StripeCustomerID       *string            `json:"stripe_customer_id"`
	StripeSubscriptionID   *string            `json:"stripe_subscription_id"`
	SubscriptionStatus     SubscriptionStatus `json:"subscription_status"`
	SubscriptionPeriodEnd  pgtype.Timestamptz `json:"subscription_period_end"`
	TrialEndsAt            pgtype.Timestamptz `json:"trial_ends_at"`
	FilesLimit             int32              `json:"files_limit"`
	MaxFileSize            int64              `json:"max_file_size"`
	TransformationsCount   int32              `json:"transformations_count"`
	TransformationsLimit   int32              `json:"transformations_limit"`
	TransformationsResetAt pgtype.Timestamptz `json:"transformations_reset_at"`
}

func (q *Queries) GetUserBillingInfo(ctx context.Context, id pgtype.UUID) (GetUserBillingInfoRow, error) {
	row := q.db.QueryRow(ctx, getUserBillingInfo, id)
	var i GetUserBillingInfoRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.SubscriptionTier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionPeriodEnd,
		&i.TrialEndsAt,
		&i.FilesLimit,
		&i.MaxFileSize,
		&i.TransformationsCount,
		&i.TransformationsLimit,
		&i.TransformationsResetAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, avatar_url, role, subscription_tier, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_period_end, trial_ends_at, files_limit, max_file_size, storage_limit_bytes, storage_used_bytes, transformations_count, transformations_limit, transformations_reset_at, email_verified_at, onboarding_completed_at, onboarding_steps, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.SubscriptionTier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionPeriodEnd,
		&i.TrialEndsAt,
		&i.FilesLimit,
		&i.MaxFileSize,
		&i.StorageLimitBytes,
		&i.StorageUsedBytes,
		&i.TransformationsCount,
		&i.TransformationsLimit,
		&i.TransformationsResetAt,
		&i.EmailVerifiedAt,
		&i.OnboardingCompletedAt,
		&i.OnboardingSteps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, avatar_url, role, subscription_tier, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_period_end, trial_ends_at, files_limit, max_file_size, storage_limit_bytes, storage_used_bytes, transformations_count, transformations_limit, transformations_reset_at, email_verified_at, onboarding_completed_at, onboarding_steps, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.SubscriptionTier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionPeriodEnd,
		&i.TrialEndsAt,
		&i.FilesLimit,
		&i.MaxFileSize,
		&i.StorageLimitBytes,
		&i.StorageUsedBytes,
		&i.TransformationsCount,
		&i.TransformationsLimit,
		&i.TransformationsResetAt,
		&i.EmailVerifiedAt,
		&i.OnboardingCompletedAt,
		&i.OnboardingSteps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByStripeCustomerID = `-- name: GetUserByStripeCustomerID :one
SELECT id, email, password_hash, name, avatar_url, role, subscription_tier, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_period_end, trial_ends_at, files_limit, max_file_size, storage_limit_bytes, storage_used_bytes, transformations_count, transformations_limit, transformations_reset_at, email_verified_at, onboarding_completed_at, onboarding_steps, created_at, updated_at, deleted_at FROM users
WHERE stripe_customer_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByStripeCustomerID(ctx context.Context, stripeCustomerID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByStripeCustomerID, stripeCustomerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.SubscriptionTier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionPeriodEnd,
		&i.TrialEndsAt,
		&i.FilesLimit,
		&i.MaxFileSize,
		&i.StorageLimitBytes,
		&i.StorageUsedBytes,
		&i.TransformationsCount,
		&i.TransformationsLimit,
		&i.TransformationsResetAt,
		&i.EmailVerifiedAt,
		&i.OnboardingCompletedAt,
		&i.OnboardingSteps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserFilesCount = `-- name: GetUserFilesCount :one
SELECT COUNT(*) FROM files
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserFilesCount(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUserFilesCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT role FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserRole(ctx context.Context, id pgtype.UUID) (UserRole, error) {
	row := q.db.QueryRow(ctx, getUserRole, id)
	var role UserRole
	err := row.Scan(&role)
	return role, err
}

const getUserStorageQuota = `-- name: GetUserStorageQuota :one
SELECT id, storage_limit_bytes, storage_used_bytes
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

type GetUserStorageQuotaRow struct {
	ID                pgtype.UUID `json:"id"`
	StorageLimitBytes int64       `json:"storage_limit_bytes"`
	StorageUsedBytes  int64       `json:"storage_used_bytes"`
}

func (q *Queries) GetUserStorageQuota(ctx context.Context, id pgtype.UUID) (GetUserStorageQuotaRow, error) {
	row := q.db.QueryRow(ctx, getUserStorageQuota, id)
	var i GetUserStorageQuotaRow
	err := row.Scan(&i.ID, &i.StorageLimitBytes, &i.StorageUsedBytes)
	return i, err
}

const getUserSubscriptionTier = `-- name: GetUserSubscriptionTier :one
SELECT subscription_tier FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserSubscriptionTier(ctx context.Context, id pgtype.UUID) (SubscriptionTier, error) {
	row := q.db.QueryRow(ctx, getUserSubscriptionTier, id)
	var subscription_tier SubscriptionTier
	err := row.Scan(&subscription_tier)
	return subscription_tier, err
}

const getUserTotalStorageUsage = `-- name: GetUserTotalStorageUsage :one
SELECT COALESCE(SUM(size_bytes), 0)::bigint AS total_bytes
FROM files
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserTotalStorageUsage(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUserTotalStorageUsage, userID)
	var total_bytes int64
	err := row.Scan(&total_bytes)
	return total_bytes, err
}

const incrementUserStorageUsed = `-- name: IncrementUserStorageUsed :exec
UPDATE users
SET storage_used_bytes = storage_used_bytes + $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type IncrementUserStorageUsedParams struct {
	ID               pgtype.UUID `json:"id"`
	StorageUsedBytes int64       `json:"storage_used_bytes"`
}

func (q *Queries) IncrementUserStorageUsed(ctx context.Context, arg IncrementUserStorageUsedParams) error {
	_, err := q.db.Exec(ctx, incrementUserStorageUsed, arg.ID, arg.StorageUsedBytes)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, name, avatar_url, role, subscription_tier, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_period_end, trial_ends_at, files_limit, max_file_size, storage_limit_bytes, storage_used_bytes, transformations_count, transformations_limit, transformations_reset_at, email_verified_at, onboarding_completed_at, onboarding_steps, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.AvatarUrl,
			&i.Role,
			&i.SubscriptionTier,
			&i.StripeCustomerID,
			&i.StripeSubscriptionID,
			&i.SubscriptionStatus,
			&i.SubscriptionPeriodEnd,
			&i.TrialEndsAt,
			&i.FilesLimit,
			&i.MaxFileSize,
			&i.StorageLimitBytes,
			&i.StorageUsedBytes,
			&i.TransformationsCount,
			&i.TransformationsLimit,
			&i.TransformationsResetAt,
			&i.EmailVerifiedAt,
			&i.OnboardingCompletedAt,
			&i.OnboardingSteps,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersForAdmin = `-- name: ListUsersForAdmin :many
SELECT
    id, email, name, avatar_url, role,
    subscription_tier, subscription_status,
    files_limit, storage_used_bytes, storage_limit_bytes,
    transformations_count, transformations_limit,
    created_at
FROM users
WHERE deleted_at IS NULL
    AND ($1::text = '' OR email ILIKE '%' || $1 || '%' OR name ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersForAdminParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListUsersForAdminRow struct {
	ID                   pgtype.UUID        `json:"id"`
	Email                string             `json:"email"`
	Name                 string             `json:"name"`
	AvatarUrl            *string            `json:"avatar_url"`
	Role                 UserRole           `json:"role"`
	SubscriptionTier     SubscriptionTier   `json:"subscription_tier"`
	SubscriptionStatus   SubscriptionStatus `json:"subscription_status"`
	FilesLimit           int32              `json:"files_limit"`
	StorageUsedBytes     int64              `json:"storage_used_bytes"`
	StorageLimitBytes    int64              `json:"storage_limit_bytes"`
	TransformationsCount int32              `json:"transformations_count"`
	TransformationsLimit int32              `json:"transformations_limit"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsersForAdmin(ctx context.Context, arg ListUsersForAdminParams) ([]ListUsersForAdminRow, error) {
	rows, err := q.db.Query(ctx, listUsersForAdmin, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersForAdminRow
	for rows.Next() {
		var i ListUsersForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
			&i.Role,
			&i.SubscriptionTier,
			&i.SubscriptionStatus,
			&i.FilesLimit,
			&i.StorageUsedBytes,
			&i.StorageLimitBytes,
			&i.TransformationsCount,
			&i.TransformationsLimit,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startUserTrial = `-- name: StartUserTrial :one
UPDATE users
SET 
    subscription_tier = 'pro',
    subscription_status = 'trialing',
    trial_ends_at = $2,
    files_limit = 2000,
    max_file_size = 104857600,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, name, avatar_url, role, subscription_tier, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_period_end, trial_ends_at, files_limit, max_file_size, storage_limit_bytes, storage_used_bytes, transformations_count, transformations_limit, transformations_reset_at, email_verified_at, onboarding_completed_at, onboarding_steps, created_at, updated_at, deleted_at
`

type StartUserTrialParams struct {
	ID          pgtype.UUID        `json:"id"`
	TrialEndsAt pgtype.Timestamptz `json:"trial_ends_at"`
}

func (q *Queries) StartUserTrial(ctx context.Context, arg StartUserTrialParams) (User, error) {
	row := q.db.QueryRow(ctx, startUserTrial, arg.ID, arg.TrialEndsAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.SubscriptionTier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionPeriodEnd,
		&i.TrialEndsAt,
		&i.FilesLimit,
		&i.MaxFileSize,
		&i.StorageLimitBytes,
		&i.StorageUsedBytes,
		&i.TransformationsCount,
		&i.TransformationsLimit,
		&i.TransformationsResetAt,
		&i.EmailVerifiedAt,
		&i.OnboardingCompletedAt,
		&i.OnboardingSteps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, avatar_url = $3, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, name, avatar_url, role, subscription_tier, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_period_end, trial_ends_at, files_limit, max_file_size, storage_limit_bytes, storage_used_bytes, transformations_count, transformations_limit, transformations_reset_at, email_verified_at, onboarding_completed_at, onboarding_steps, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID        pgtype.UUID `json:"id"`
	Name      string      `json:"name"`
	AvatarUrl *string     `json:"avatar_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.SubscriptionTier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionPeriodEnd,
		&i.TrialEndsAt,
		&i.FilesLimit,
		&i.MaxFileSize,
		&i.StorageLimitBytes,
		&i.StorageUsedBytes,
		&i.TransformationsCount,
		&i.TransformationsLimit,
		&i.TransformationsResetAt,
		&i.EmailVerifiedAt,
		&i.OnboardingCompletedAt,
		&i.OnboardingSteps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash *string     `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserStorageLimit = `-- name: UpdateUserStorageLimit :exec
UPDATE users
SET storage_limit_bytes = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserStorageLimitParams struct {
	ID                pgtype.UUID `json:"id"`
	StorageLimitBytes int64       `json:"storage_limit_bytes"`
}

func (q *Queries) UpdateUserStorageLimit(ctx context.Context, arg UpdateUserStorageLimitParams) error {
	_, err := q.db.Exec(ctx, updateUserStorageLimit, arg.ID, arg.StorageLimitBytes)
	return err
}

const updateUserStorageUsed = `-- name: UpdateUserStorageUsed :exec
UPDATE users
SET storage_used_bytes = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserStorageUsedParams struct {
	ID               pgtype.UUID `json:"id"`
	StorageUsedBytes int64       `json:"storage_used_bytes"`
}

func (q *Queries) UpdateUserStorageUsed(ctx context.Context, arg UpdateUserStorageUsedParams) error {
	_, err := q.db.Exec(ctx, updateUserStorageUsed, arg.ID, arg.StorageUsedBytes)
	return err
}

const updateUserStripeCustomer = `-- name: UpdateUserStripeCustomer :one
UPDATE users
SET stripe_customer_id = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, name, avatar_url, role, subscription_tier, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_period_end, trial_ends_at, files_limit, max_file_size, storage_limit_bytes, storage_used_bytes, transformations_count, transformations_limit, transformations_reset_at, email_verified_at, onboarding_completed_at, onboarding_steps, created_at, updated_at, deleted_at
`

type UpdateUserStripeCustomerParams struct {
	ID               pgtype.UUID `json:"id"`
	StripeCustomerID *string     `json:"stripe_customer_id"`
}

func (q *Queries) UpdateUserStripeCustomer(ctx context.Context, arg UpdateUserStripeCustomerParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStripeCustomer, arg.ID, arg.StripeCustomerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.SubscriptionTier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionPeriodEnd,
		&i.TrialEndsAt,
		&i.FilesLimit,
		&i.MaxFileSize,
		&i.StorageLimitBytes,
		&i.StorageUsedBytes,
		&i.TransformationsCount,
		&i.TransformationsLimit,
		&i.TransformationsResetAt,
		&i.EmailVerifiedAt,
		&i.OnboardingCompletedAt,
		&i.OnboardingSteps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserSubscription = `-- name: UpdateUserSubscription :one
UPDATE users
SET 
    stripe_subscription_id = $2,
    subscription_status = $3,
    subscription_tier = $4,
    subscription_period_end = $5,
    trial_ends_at = $6,
    files_limit = $7,
    max_file_size = $8,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, name, avatar_url, role, subscription_tier, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_period_end, trial_ends_at, files_limit, max_file_size, storage_limit_bytes, storage_used_bytes, transformations_count, transformations_limit, transformations_reset_at, email_verified_at, onboarding_completed_at, onboarding_steps, created_at, updated_at, deleted_at
`

type UpdateUserSubscriptionParams struct {
	ID                    pgtype.UUID        `json:"id"`
	StripeSubscriptionID  *string            `json:"stripe_subscription_id"`
	SubscriptionStatus    SubscriptionStatus `json:"subscription_status"`
	SubscriptionTier      SubscriptionTier   `json:"subscription_tier"`
	SubscriptionPeriodEnd pgtype.Timestamptz `json:"subscription_period_end"`
	TrialEndsAt           pgtype.Timestamptz `json:"trial_ends_at"`
	FilesLimit            int32              `json:"files_limit"`
	MaxFileSize           int64              `json:"max_file_size"`
}

func (q *Queries) UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserSubscription,
		arg.ID,
		arg.StripeSubscriptionID,
		arg.SubscriptionStatus,
		arg.SubscriptionTier,
		arg.SubscriptionPeriodEnd,
		arg.TrialEndsAt,
		arg.FilesLimit,
		arg.MaxFileSize,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.SubscriptionTier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionPeriodEnd,
		&i.TrialEndsAt,
		&i.FilesLimit,
		&i.MaxFileSize,
		&i.StorageLimitBytes,
		&i.StorageUsedBytes,
		&i.TransformationsCount,
		&i.TransformationsLimit,
		&i.TransformationsResetAt,
		&i.EmailVerifiedAt,
		&i.OnboardingCompletedAt,
		&i.OnboardingSteps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserSubscriptionStatus = `-- name: UpdateUserSubscriptionStatus :one
UPDATE users
SET 
    subscription_status = $2,
    subscription_period_end = $3,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, name, avatar_url, role, subscription_tier, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_period_end, trial_ends_at, files_limit, max_file_size, storage_limit_bytes, storage_used_bytes, transformations_count, transformations_limit, transformations_reset_at, email_verified_at, onboarding_completed_at, onboarding_steps, created_at, updated_at, deleted_at
`

type UpdateUserSubscriptionStatusParams struct {
	ID                    pgtype.UUID        `json:"id"`
	SubscriptionStatus    SubscriptionStatus `json:"subscription_status"`
	SubscriptionPeriodEnd pgtype.Timestamptz `json:"subscription_period_end"`
}

func (q *Queries) UpdateUserSubscriptionStatus(ctx context.Context, arg UpdateUserSubscriptionStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserSubscriptionStatus, arg.ID, arg.SubscriptionStatus, arg.SubscriptionPeriodEnd)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.SubscriptionTier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionPeriodEnd,
		&i.TrialEndsAt,
		&i.FilesLimit,
		&i.MaxFileSize,
		&i.StorageLimitBytes,
		&i.StorageUsedBytes,
		&i.TransformationsCount,
		&i.TransformationsLimit,
		&i.TransformationsResetAt,
		&i.EmailVerifiedAt,
		&i.OnboardingCompletedAt,
		&i.OnboardingSteps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserSubscriptionTier = `-- name: UpdateUserSubscriptionTier :one
UPDATE users
SET subscription_tier = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, name, avatar_url, role, subscription_tier, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_period_end, trial_ends_at, files_limit, max_file_size, storage_limit_bytes, storage_used_bytes, transformations_count, transformations_limit, transformations_reset_at, email_verified_at, onboarding_completed_at, onboarding_steps, created_at, updated_at, deleted_at
`

type UpdateUserSubscriptionTierParams struct {
	ID               pgtype.UUID      `json:"id"`
	SubscriptionTier SubscriptionTier `json:"subscription_tier"`
}

func (q *Queries) UpdateUserSubscriptionTier(ctx context.Context, arg UpdateUserSubscriptionTierParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserSubscriptionTier, arg.ID, arg.SubscriptionTier)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.SubscriptionTier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionPeriodEnd,
		&i.TrialEndsAt,
		&i.FilesLimit,
		&i.MaxFileSize,
		&i.StorageLimitBytes,
		&i.StorageUsedBytes,
		&i.TransformationsCount,
		&i.TransformationsLimit,
		&i.TransformationsResetAt,
		&i.EmailVerifiedAt,
		&i.OnboardingCompletedAt,
		&i.OnboardingSteps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserTier = `-- name: UpdateUserTier :one
UPDATE users
SET
    subscription_tier = $2,
    subscription_status = CASE
        WHEN $2 = 'free' THEN 'none'
        ELSE 'active'
    END,
    files_limit = CASE
        WHEN $2 = 'free' THEN 100
        WHEN $2 = 'pro' THEN 2000
        WHEN $2 = 'enterprise' THEN -1
    END,
    max_file_size = CASE
        WHEN $2 = 'free' THEN 10485760
        WHEN $2 = 'pro' THEN 104857600
        WHEN $2 = 'enterprise' THEN 10737418240
    END,
    storage_limit_bytes = CASE
        WHEN $2 = 'free' THEN 1073741824
        WHEN $2 = 'pro' THEN 107374182400
        WHEN $2 = 'enterprise' THEN 1099511627776
    END,
    transformations_limit = CASE
        WHEN $2 = 'free' THEN 100
        WHEN $2 = 'pro' THEN 10000
        WHEN $2 = 'enterprise' THEN -1
    END,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, name, avatar_url, role, subscription_tier, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_period_end, trial_ends_at, files_limit, max_file_size, storage_limit_bytes, storage_used_bytes, transformations_count, transformations_limit, transformations_reset_at, email_verified_at, onboarding_completed_at, onboarding_steps, created_at, updated_at, deleted_at
`

type UpdateUserTierParams struct {
	ID               pgtype.UUID      `json:"id"`
	SubscriptionTier SubscriptionTier `json:"subscription_tier"`
}

func (q *Queries) UpdateUserTier(ctx context.Context, arg UpdateUserTierParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserTier, arg.ID, arg.SubscriptionTier)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.SubscriptionTier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionPeriodEnd,
		&i.TrialEndsAt,
		&i.FilesLimit,
		&i.MaxFileSize,
		&i.StorageLimitBytes,
		&i.StorageUsedBytes,
		&i.TransformationsCount,
		&i.TransformationsLimit,
		&i.TransformationsResetAt,
		&i.EmailVerifiedAt,
		&i.OnboardingCompletedAt,
		&i.OnboardingSteps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserToEnterprise = `-- name: UpdateUserToEnterprise :one
UPDATE users
SET
    subscription_tier = 'enterprise',
    subscription_status = 'active',
    files_limit = -1,
    max_file_size = 10737418240,
    storage_limit_bytes = 1099511627776,
    transformations_limit = -1,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, name, avatar_url, role, subscription_tier, stripe_customer_id, stripe_subscription_id, subscription_status, subscription_period_end, trial_ends_at, files_limit, max_file_size, storage_limit_bytes, storage_used_bytes, transformations_count, transformations_limit, transformations_reset_at, email_verified_at, onboarding_completed_at, onboarding_steps, created_at, updated_at, deleted_at
`

func (q *Queries) UpdateUserToEnterprise(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, updateUserToEnterprise, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.AvatarUrl,
		&i.Role,
		&i.SubscriptionTier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionPeriodEnd,
		&i.TrialEndsAt,
		&i.FilesLimit,
		&i.MaxFileSize,
		&i.StorageLimitBytes,
		&i.StorageUsedBytes,
		&i.TransformationsCount,
		&i.TransformationsLimit,
		&i.TransformationsResetAt,
		&i.EmailVerifiedAt,
		&i.OnboardingCompletedAt,
		&i.OnboardingSteps,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users
SET email_verified_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, id)
	return err
}
