// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserSettings = `-- name: CreateUserSettings :one
INSERT INTO user_settings (user_id)
VALUES ($1)
RETURNING id, user_id, email_notifications, processing_alerts, marketing_emails, default_retention_days, auto_delete_originals, created_at, updated_at
`

func (q *Queries) CreateUserSettings(ctx context.Context, userID pgtype.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, createUserSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmailNotifications,
		&i.ProcessingAlerts,
		&i.MarketingEmails,
		&i.DefaultRetentionDays,
		&i.AutoDeleteOriginals,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT id, user_id, email_notifications, processing_alerts, marketing_emails, default_retention_days, auto_delete_originals, created_at, updated_at FROM user_settings
WHERE user_id = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, userID pgtype.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, getUserSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmailNotifications,
		&i.ProcessingAlerts,
		&i.MarketingEmails,
		&i.DefaultRetentionDays,
		&i.AutoDeleteOriginals,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFileSettings = `-- name: UpdateFileSettings :one
UPDATE user_settings
SET default_retention_days = $2,
    auto_delete_originals = $3,
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, email_notifications, processing_alerts, marketing_emails, default_retention_days, auto_delete_originals, created_at, updated_at
`

type UpdateFileSettingsParams struct {
	UserID               pgtype.UUID `json:"user_id"`
	DefaultRetentionDays int32       `json:"default_retention_days"`
	AutoDeleteOriginals  bool        `json:"auto_delete_originals"`
}

func (q *Queries) UpdateFileSettings(ctx context.Context, arg UpdateFileSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, updateFileSettings, arg.UserID, arg.DefaultRetentionDays, arg.AutoDeleteOriginals)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmailNotifications,
		&i.ProcessingAlerts,
		&i.MarketingEmails,
		&i.DefaultRetentionDays,
		&i.AutoDeleteOriginals,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNotificationSettings = `-- name: UpdateNotificationSettings :one
UPDATE user_settings
SET email_notifications = $2,
    processing_alerts = $3,
    marketing_emails = $4,
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, email_notifications, processing_alerts, marketing_emails, default_retention_days, auto_delete_originals, created_at, updated_at
`

type UpdateNotificationSettingsParams struct {
	UserID             pgtype.UUID `json:"user_id"`
	EmailNotifications bool        `json:"email_notifications"`
	ProcessingAlerts   bool        `json:"processing_alerts"`
	MarketingEmails    bool        `json:"marketing_emails"`
}

func (q *Queries) UpdateNotificationSettings(ctx context.Context, arg UpdateNotificationSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, updateNotificationSettings,
		arg.UserID,
		arg.EmailNotifications,
		arg.ProcessingAlerts,
		arg.MarketingEmails,
	)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmailNotifications,
		&i.ProcessingAlerts,
		&i.MarketingEmails,
		&i.DefaultRetentionDays,
		&i.AutoDeleteOriginals,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserSettings = `-- name: UpsertUserSettings :one
INSERT INTO user_settings (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET updated_at = NOW()
RETURNING id, user_id, email_notifications, processing_alerts, marketing_emails, default_retention_days, auto_delete_originals, created_at, updated_at
`

func (q *Queries) UpsertUserSettings(ctx context.Context, userID pgtype.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, upsertUserSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EmailNotifications,
		&i.ProcessingAlerts,
		&i.MarketingEmails,
		&i.DefaultRetentionDays,
		&i.AutoDeleteOriginals,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
