// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: variants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVariant = `-- name: CreateVariant :one
INSERT INTO file_variants (
    file_id,
    variant_type,
    content_type,
    size_bytes,
    storage_key,
    width,
    height
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, file_id, variant_type, content_type, size_bytes, storage_key, width, height, created_at
`

type CreateVariantParams struct {
	FileID      pgtype.UUID `json:"file_id"`
	VariantType VariantType `json:"variant_type"`
	ContentType string      `json:"content_type"`
	SizeBytes   int64       `json:"size_bytes"`
	StorageKey  string      `json:"storage_key"`
	Width       *int32      `json:"width"`
	Height      *int32      `json:"height"`
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (FileVariant, error) {
	row := q.db.QueryRow(ctx, createVariant,
		arg.FileID,
		arg.VariantType,
		arg.ContentType,
		arg.SizeBytes,
		arg.StorageKey,
		arg.Width,
		arg.Height,
	)
	var i FileVariant
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.VariantType,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVariant = `-- name: DeleteVariant :exec
DELETE FROM file_variants
WHERE id = $1
`

func (q *Queries) DeleteVariant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVariant, id)
	return err
}

const deleteVariantsByFile = `-- name: DeleteVariantsByFile :exec
DELETE FROM file_variants
WHERE file_id = $1
`

func (q *Queries) DeleteVariantsByFile(ctx context.Context, fileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVariantsByFile, fileID)
	return err
}

const getThumbnailsForFiles = `-- name: GetThumbnailsForFiles :many
SELECT file_id, storage_key, content_type, size_bytes
FROM file_variants
WHERE file_id = ANY($1::uuid[]) AND variant_type = 'thumbnail'
`

type GetThumbnailsForFilesRow struct {
	FileID      pgtype.UUID `json:"file_id"`
	StorageKey  string      `json:"storage_key"`
	ContentType string      `json:"content_type"`
	SizeBytes   int64       `json:"size_bytes"`
}

func (q *Queries) GetThumbnailsForFiles(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetThumbnailsForFilesRow, error) {
	rows, err := q.db.Query(ctx, getThumbnailsForFiles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetThumbnailsForFilesRow
	for rows.Next() {
		var i GetThumbnailsForFilesRow
		if err := rows.Scan(
			&i.FileID,
			&i.StorageKey,
			&i.ContentType,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVariant = `-- name: GetVariant :one
SELECT id, file_id, variant_type, content_type, size_bytes, storage_key, width, height, created_at FROM file_variants
WHERE file_id = $1 AND variant_type = $2
`

type GetVariantParams struct {
	FileID      pgtype.UUID `json:"file_id"`
	VariantType VariantType `json:"variant_type"`
}

func (q *Queries) GetVariant(ctx context.Context, arg GetVariantParams) (FileVariant, error) {
	row := q.db.QueryRow(ctx, getVariant, arg.FileID, arg.VariantType)
	var i FileVariant
	err := row.Scan(
		&i.ID,
		&i.FileID,
		&i.VariantType,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.Width,
		&i.Height,
		&i.CreatedAt,
	)
	return i, err
}

const getVariantTypes = `-- name: GetVariantTypes :many
SELECT variant_type FROM file_variants
WHERE file_id = $1
`

func (q *Queries) GetVariantTypes(ctx context.Context, fileID pgtype.UUID) ([]VariantType, error) {
	rows, err := q.db.Query(ctx, getVariantTypes, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VariantType
	for rows.Next() {
		var variant_type VariantType
		if err := rows.Scan(&variant_type); err != nil {
			return nil, err
		}
		items = append(items, variant_type)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasVariant = `-- name: HasVariant :one
SELECT EXISTS(
    SELECT 1 FROM file_variants
    WHERE file_id = $1 AND variant_type = $2
) AS exists
`

type HasVariantParams struct {
	FileID      pgtype.UUID `json:"file_id"`
	VariantType VariantType `json:"variant_type"`
}

func (q *Queries) HasVariant(ctx context.Context, arg HasVariantParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasVariant, arg.FileID, arg.VariantType)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listVariantsByFile = `-- name: ListVariantsByFile :many
SELECT id, file_id, variant_type, content_type, size_bytes, storage_key, width, height, created_at FROM file_variants
WHERE file_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListVariantsByFile(ctx context.Context, fileID pgtype.UUID) ([]FileVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsByFile, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileVariant
	for rows.Next() {
		var i FileVariant
		if err := rows.Scan(
			&i.ID,
			&i.FileID,
			&i.VariantType,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
