// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: zip_downloads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingZipDownloadsByUser = `-- name: CountPendingZipDownloadsByUser :one
SELECT COUNT(*) FROM zip_downloads
WHERE user_id = $1 AND status IN ('pending', 'running')
`

func (q *Queries) CountPendingZipDownloadsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingZipDownloadsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createZipDownload = `-- name: CreateZipDownload :one
INSERT INTO zip_downloads (user_id, file_ids, status)
VALUES ($1, $2, 'pending')
RETURNING id, user_id, file_ids, status, storage_key, size_bytes, download_url, expires_at, error_message, created_at, completed_at
`

type CreateZipDownloadParams struct {
	UserID  pgtype.UUID   `json:"user_id"`
	FileIds []pgtype.UUID `json:"file_ids"`
}

func (q *Queries) CreateZipDownload(ctx context.Context, arg CreateZipDownloadParams) (ZipDownload, error) {
	row := q.db.QueryRow(ctx, createZipDownload, arg.UserID, arg.FileIds)
	var i ZipDownload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileIds,
		&i.Status,
		&i.StorageKey,
		&i.SizeBytes,
		&i.DownloadUrl,
		&i.ExpiresAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteExpiredZipDownloads = `-- name: DeleteExpiredZipDownloads :exec
DELETE FROM zip_downloads
WHERE expires_at IS NOT NULL AND expires_at < NOW()
`

func (q *Queries) DeleteExpiredZipDownloads(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredZipDownloads)
	return err
}

const getZipDownload = `-- name: GetZipDownload :one
SELECT id, user_id, file_ids, status, storage_key, size_bytes, download_url, expires_at, error_message, created_at, completed_at FROM zip_downloads
WHERE id = $1
`

func (q *Queries) GetZipDownload(ctx context.Context, id pgtype.UUID) (ZipDownload, error) {
	row := q.db.QueryRow(ctx, getZipDownload, id)
	var i ZipDownload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileIds,
		&i.Status,
		&i.StorageKey,
		&i.SizeBytes,
		&i.DownloadUrl,
		&i.ExpiresAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getZipDownloadByUser = `-- name: GetZipDownloadByUser :one
SELECT id, user_id, file_ids, status, storage_key, size_bytes, download_url, expires_at, error_message, created_at, completed_at FROM zip_downloads
WHERE id = $1 AND user_id = $2
`

type GetZipDownloadByUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetZipDownloadByUser(ctx context.Context, arg GetZipDownloadByUserParams) (ZipDownload, error) {
	row := q.db.QueryRow(ctx, getZipDownloadByUser, arg.ID, arg.UserID)
	var i ZipDownload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FileIds,
		&i.Status,
		&i.StorageKey,
		&i.SizeBytes,
		&i.DownloadUrl,
		&i.ExpiresAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listZipDownloadsByUser = `-- name: ListZipDownloadsByUser :many
SELECT id, user_id, file_ids, status, storage_key, size_bytes, download_url, expires_at, error_message, created_at, completed_at FROM zip_downloads
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListZipDownloadsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListZipDownloadsByUser(ctx context.Context, arg ListZipDownloadsByUserParams) ([]ZipDownload, error) {
	rows, err := q.db.Query(ctx, listZipDownloadsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ZipDownload
	for rows.Next() {
		var i ZipDownload
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FileIds,
			&i.Status,
			&i.StorageKey,
			&i.SizeBytes,
			&i.DownloadUrl,
			&i.ExpiresAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateZipDownloadCompleted = `-- name: UpdateZipDownloadCompleted :exec
UPDATE zip_downloads
SET status = 'completed',
    storage_key = $2,
    size_bytes = $3,
    download_url = $4,
    expires_at = $5,
    completed_at = NOW()
WHERE id = $1
`

type UpdateZipDownloadCompletedParams struct {
	ID          pgtype.UUID        `json:"id"`
	StorageKey  *string            `json:"storage_key"`
	SizeBytes   *int64             `json:"size_bytes"`
	DownloadUrl *string            `json:"download_url"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpdateZipDownloadCompleted(ctx context.Context, arg UpdateZipDownloadCompletedParams) error {
	_, err := q.db.Exec(ctx, updateZipDownloadCompleted,
		arg.ID,
		arg.StorageKey,
		arg.SizeBytes,
		arg.DownloadUrl,
		arg.ExpiresAt,
	)
	return err
}

const updateZipDownloadFailed = `-- name: UpdateZipDownloadFailed :exec
UPDATE zip_downloads
SET status = 'failed',
    error_message = $2,
    completed_at = NOW()
WHERE id = $1
`

type UpdateZipDownloadFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage *string     `json:"error_message"`
}

func (q *Queries) UpdateZipDownloadFailed(ctx context.Context, arg UpdateZipDownloadFailedParams) error {
	_, err := q.db.Exec(ctx, updateZipDownloadFailed, arg.ID, arg.ErrorMessage)
	return err
}

const updateZipDownloadRunning = `-- name: UpdateZipDownloadRunning :exec
UPDATE zip_downloads
SET status = 'running'
WHERE id = $1
`

func (q *Queries) UpdateZipDownloadRunning(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateZipDownloadRunning, id)
	return err
}
